env:
  - dev
  - prod
dir:
  assets: "/assets"
  assetsSass: "/assets/sass"
  assetsJade: "/assets/jade"
  assetsImg: "/assets/img"
  build:  "/build"
  buildCss: "/build/css"
  buildImg: "/build/img"
gulp:
  compass:
    img: "../img"
  image:
    optimizationLevel: 0
webpack:
  entry:
    - "./src/index.jsx"
  output:
    path: "./build"
    publicPath: "/"
    filename: "bundle.js"
  module:
    loaders:
      - test: ".jsx?$"
        exclude: "node_modules"
        loader: "babel"
  resolve:
    extensions:
      - ""
      - ".js"
      - ".jsx"
  devServer:
    hot: false
    contentBase: "./build"
  plugins:
    hasHotModuleReplacement: false