webpack:
  entry:
    - "webpack-dev-server/client?http://localhost:8080"
    - "webpack/hot/only-dev-server"
    - "./src/index.jsx"
  output:
    path: "./build"
    publicPath: "/"
    filename: "bundle.js"
  module:
    loaders:
      - test: ".jsx?$"
        include:
          - "./src"
          - "./node_modules/react-circular-progress"
        loader: "react-hot!babel"
      - test: ".css$"
        exclude: "node_modules"
        loader: "style!css"
  resolve:
    extensions:
      - ""
      - ".js"
      - ".jsx"
  devServer:
    hot: true
  plugins:
    hasHotModuleReplacement: true